version: '3.9'

services:
  postgres:
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=course_work
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  app:
    image: adoptopenjdk:11-jre-hotspot
    volumes:
      - ./target/course_work-0.0.1-SNAPSHOT.jar:/app.jar
    command: java -jar app.jar
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/course_work
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - '8084:8084'
    depends_on:
      postgres:
        condition: service_healthy
  front_end:
    build: ./src/main/resources/front_end/dogs_shelter_frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
