-- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    password character varying(255) COLLATE pg_catalog."default",
    role character varying(255) COLLATE pg_catalog."default",
    username character varying(255) COLLATE pg_catalog."default",
    phone_number character varying(12) COLLATE pg_catalog."default",
    activity boolean DEFAULT true,
    initials character varying(45) COLLATE pg_catalog."default",
    CONSTRAINT users_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;

-- Table: public.orders

-- DROP TABLE IF EXISTS public.orders;

CREATE TABLE IF NOT EXISTS public.orders
(
    user_id integer NOT NULL,
    dog_id integer NOT NULL,
    id bigint NOT NULL DEFAULT nextval('orders_id_seq'::regclass),
    CONSTRAINT orders_pk PRIMARY KEY (id),
    CONSTRAINT dog_id FOREIGN KEY (dog_id)
        REFERENCES public.dogs (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT user_id FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE CASCADE
        ON DELETE CASCADE
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.orders
    OWNER to postgres;

-- Table: public.dogs

-- DROP TABLE IF EXISTS public.dogs;

CREATE TABLE IF NOT EXISTS public.dogs
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    breed character varying(255) COLLATE pg_catalog."default",
    img character varying(255) COLLATE pg_catalog."default",
    name character varying(255) COLLATE pg_catalog."default",
    age integer,
    description character varying(255) COLLATE pg_catalog."default",
    ordered boolean DEFAULT false,
    gender character varying(7) COLLATE pg_catalog."default",
    CONSTRAINT dogs_pkey PRIMARY KEY (id)
)

    TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.dogs
    OWNER to postgres;