create table dogs
(
    id          bigint generated by default as identity (maxvalue 2147483647)
        primary key,
    breed       varchar(255),
    img         varchar(255),
    name        varchar(255),
    age         integer,
    description varchar(255),
    ordered     boolean default false,
    gender      varchar(7)
);

alter table dogs
    owner to postgres;

INSERT INTO public.dogs (id, breed, img, name, age, description, ordered, gender) VALUES (67, 'Акита-ину', 'https://sobakovod.club/uploads/posts/2021-12/1640743526_1-sobakovod-club-p-sobaki-shchenki-porodi-akita-inu-1.jpg', 'Пушистик', 2, 'Красавец без плохих привычек :)', false, 'Мальчик');
INSERT INTO public.dogs (id, breed, img, name, age, description, ordered, gender) VALUES (68, 'Кокер-спаниэль', 'https://img.aboutanimal.ru/images/2020/05/24/mozhno-li-sobake-arbuz-1590324818.jpg', 'Арбузик', 3, 'Такую кличку получил за свою любовь к арбузам!', false, 'Мальчик');
INSERT INTO public.dogs (id, breed, img, name, age, description, ordered, gender) VALUES (66, 'Той Терьер', 'https://avatars.dzeninfra.ru/get-zen_doc/1873797/pub_61b05381630d636a51216ed9_61b056f0abdb33036aee4616/scale_1200', 'Барсик', 3, 'Красавчик!', false, 'Мальчик');
INSERT INTO public.dogs (id, breed, img, name, age, description, ordered, gender) VALUES (65, 'Бассенджи', 'http://mirsobak.net/wp-content/uploads/basenji-11.jpg', 'Шерри', 14, 'Добрая', true, 'Девочка');
INSERT INTO public.dogs (id, breed, img, name, age, description, ordered, gender) VALUES (59, 'Бассенджи', 'http://mirsobak.net/wp-content/uploads/basenji-11.jpg', 'Клиф', 13, 'Старенький но очень добрый и вежливый', false, 'Мальчик');
INSERT INTO public.dogs (id, breed, img, name, age, description, ordered, gender) VALUES (64, 'Бассенджи', 'http://mirsobak.net/wp-content/uploads/basenji-11.jpg', 'Шерри', 14, 'Добрая', false, 'Девочка');
INSERT INTO public.dogs (id, breed, img, name, age, description, ordered, gender) VALUES (63, 'Бассенджи', 'http://mirsobak.net/wp-content/uploads/basenji-11.jpg', 'Шерри', 14, 'Добрая', false, 'Девочка');
